// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBZRKmY0qTpoatnZYx8z6IjnoCQzwYvY',
    appId: '1:931096297493:web:d05368c2c27bf957ab0e1c',
    messagingSenderId: '931096297493',
    projectId: 'otoserve-49e20',
    authDomain: 'otoserve-49e20.firebaseapp.com',
    storageBucket: 'otoserve-49e20.appspot.com',
    measurementId: 'G-7PS6XZFH21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVZD0kcr5Jl51W78_2SyqdLOX2vuMWDM',
    appId: '1:931096297493:android:7dbe01554bebaf1dab0e1c',
    messagingSenderId: '931096297493',
    projectId: 'otoserve-49e20',
    storageBucket: 'otoserve-49e20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBow3MMjrEPLTl4AJjdk6V7xyV7BWyehSc',
    appId: '1:931096297493:ios:15fe467667555d07ab0e1c',
    messagingSenderId: '931096297493',
    projectId: 'otoserve-49e20',
    storageBucket: 'otoserve-49e20.appspot.com',
    iosBundleId: 'com.example.otoserve',
  );
}
